let express=require('express')
const { colorRoutes } = require('./colorRoutes')
const { materialRoutes } = require('./materialRoutes')
const { faqRoutes } = require('./faqRoutes')
const { countryRoutes } = require('./countryRoutes')
const { categoryRoutes } = require('./categoryRoutes')
const { subCategoryRoutes } = require('./subCategoryRoutes')
const { subsubCatRoutes } = require('./subsubCategoryRoutes')
const { productRoutes } = require('./productRoutes')
const { whyChooseUsRoutes } = require('./whyChooseUsRoutes')
const { sliderRoutes } = require('./sliderRoutes')
const { adminAuthRoutes } = require('./adminAuthRoutes')
const { cprofileRoutes } = require('./companyProfileRoutes')
const { adminProfileRoutes } = require('./adminProfileRoutes')
const { userAuthRoutes } = require('./userAuthRoutes')
let adminRouter=express.Router()

adminRouter.use('/adminauth',adminAuthRoutes)
adminRouter.use('/color',colorRoutes)
adminRouter.use('/material',materialRoutes)
adminRouter.use('/faq',faqRoutes)
adminRouter.use('/country',countryRoutes)
adminRouter.use('/category',categoryRoutes)
adminRouter.use('/subcategory',subCategoryRoutes)
adminRouter.use('/subsubcategory',subsubCatRoutes)
adminRouter.use('/product',productRoutes)
adminRouter.use('/testimonial',productRoutes)
adminRouter.use('/whychooseus',whyChooseUsRoutes)
adminRouter.use('/slider',sliderRoutes)
adminRouter.use('/companyp',cprofileRoutes)
adminRouter.use('/adminprofile',adminProfileRoutes)
adminRouter.use('/web-user',userAuthRoutes)

module.exports={adminRouter}

